apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  metadata:
    spec:
      containers:
      - name: hello-world-pod
        image: hello-world
        ports:
        - containerPort: 80
